services:

  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - eventhub
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.6.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eventhub
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    #ports:
      #- "8001:8001"
    env_file:
      - .env
    environment:
      - MONGO_DB.URL=mongodb://mongodb:27017
      - MONGO_DB.DB_NAME=eventhub
      - REDIS_CONFIG.URL=redis://redis:6379
      - REDIS_CONFIG.DB=0
      - REDIS_CONFIG.PASSWORD=
    networks:
      - eventhub
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: taskiq worker app.tasks.broker:broker
    env_file:
      - .env
    environment:
      - MONGO_DB.URL=mongodb://mongodb:27017
      - MONGO_DB.DB_NAME=eventhub
      - REDIS_CONFIG.URL=redis://redis:6379
      - REDIS_CONFIG.DB=0
      - REDIS_CONFIG.PASSWORD=
    networks:
      - eventhub
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'taskiq worker' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - eventhub
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q https://localhost:443 --no-check-certificate || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  nginx_ssl:
  mongodb_data:
  redis_data:

networks:
  eventhub:
    driver: bridge