services:

  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - MONGO_DB.URL=mongodb://mongodb:27017
      - MONGO_DB.DB_NAME=eventhub
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: